import Config

# Configure your database
config :podcast_mcp, PodcastMcp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "podcast_mcp_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :podcast_mcp, PodcastMcpWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "QnV5yjNGeNVykMPwZ5GvT2PJoe3jlBlgBfCmZGQyIp2GVPY7TXGVdmxIn/ozVCtG",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:podcast_mcp, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:podcast_mcp, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :podcast_mcp, PodcastMcpWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/podcast_mcp_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :podcast_mcp, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false


# RabbitMQ Configuration
config :podcast_mcp, :rabbit_mq,
  # For development, connecting to RabbitMQ running in Docker on localhost
  # Default RabbitMQ user/pass is guest/guest
  url: System.get_env("RABBITMQ_URL") || "amqp://guest:guest@localhost:5672",
  # You can also configure host, port, username, password, vhost separately
  # host: System.get_env("RABBITMQ_HOST") || "localhost",
  # port: String.to_integer(System.get_env("RABBITMQ_PORT") || "5672"),
  # username: System.get_env("RABBITMQ_USER") || "guest",
  # password: System.get_env("RABBITMQ_PASS") || "guest",
  # vhost: System.get_env("RABBITMQ_VHOST") || "/",
  # Name of the exchange where episode processing jobs will be published
  exchange_name: "podcast_processing_exchange",
  # Name of the queue for transcription tasks (workers will listen to this)
  transcription_queue_name: "transcription_tasks_queue",
  # Routing key for transcription tasks
  transcription_routing_key: "episode.transcribe"

# Example for production (config/prod.exs), using environment variables:
# config :podcast_mcp, :rabbit_mq,
#   url: System.get_env("RABBITMQ_URL"), # e.g., amqp://user:pass@your-rabbitmq-server.com:5672/your_vhost
#   exchange_name: "podcast_processing_exchange",
#   transcription_queue_name: "transcription_tasks_queue",
#   transcription_routing_key: "episode.transcribe"
